---
- name: "Force gathering facts"
  hosts: all
  gather_facts: True
  roles: []

- name: "Converge"
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: ansible-role-solr-standalone
  vars:
    solr_change_default_password: False
